Prios impl details depend on rex_form methods
rex_form_base does not provide all methods required

ERROR: UndefinedMethod - redaxo/src/core/lib/form/elements/prio.php:61:87 - Method rex_form_base::gettablename does not exist
368        $qry = 'SELECT ' . $this->labelField . ',' . $name . ' FROM ' . $this->table->getTableName() . ' WHERE 1=1';
369
370
371ERROR: UndefinedMethod - redaxo/src/core/lib/form/elements/prio.php:67:27 - Method rex_form_base::iseditmode does not exist
372        if ($this->table->isEditMode()) {
373
374
375ERROR: UndefinedMethod - redaxo/src/core/lib/form/elements/prio.php:87:28 - Method rex_form_base::iseditmode does not exist
376        if (!$this->table->isEditMode()) {
377
378
379ERROR: UndefinedMethod - redaxo/src/core/lib/form/elements/prio.php:96:27 - Method rex_form_base::equals does not exist
380        if ($this->table->equals($ep->getParam('form'))) {
381
382
383ERROR: UndefinedMethod - redaxo/src/core/lib/form/elements/prio.php:100:31 - Method rex_form_base::gettablename does not exist
384                $this->table->getTableName()